### ISSUE TITLE
Error during migration when starting with an empty database?

### ISSUE THREAD

**Issue by ssciolla** [Cvmcosta/ltijs-sequelize#5]
Hi @Cvmcosta, I was trying to update to the latest versions of `ltijs` (`~5.7.3`) and `ltijs-sequelize` (`~2.4.1`) and I ran into an issue. I am currently using `postgres`. Things seem to work fine if I have a database schema set up from running the previous version of these libraries:

```
2021-04-16T20:12:21.871Z provider:main Attempting to connect to database
2021-04-16T20:12:21.872Z provider:database Using Sequelize Database Plugin - Cvmcosta
2021-04-16T20:12:21.872Z provider:database Dialect: postgres
2021-04-16T20:12:22.194Z provider:database Performing migrations
{ event: 'migrating', name: '00_addAuthorizationServer.js' }
{
   event: 'migrated',
   name: '00_addAuthorizationServer.js',
   durationSeconds: 0.022
}
```

However, if I run the application on an empty `postgres` database, the migration errors out thusly:

```
2021-04-16T20:14:37.681Z provider:main Attempting to connect to database
2021-04-16T20:14:37.682Z provider:database Using Sequelize Database Plugin - Cvmcosta
2021-04-16T20:14:37.682Z provider:database Dialect: postgres
2021-04-16T20:14:38.316Z provider:database Performing migrations
{ event: 'migrating', name: '00_addAuthorizationServer.js' }
Error during deployment:  DatabaseError [SequelizeDatabaseError]: column "authorizationServer" of relation "platforms" already exists
```
(followed by more tracebacks, and the server and database connection shutting down)

Could you try to reproduce this error please? I could easily be missing some important step. If this is a real issue, this seems like it could be a significant blocker for new adoption and development work (where you may want to wipe out databases, or start from scratch often).

Thanks for the assistance!

**Comment by Cvmcosta** [comment]
Hello @ssciolla! You are correct. I forgot to remove the change described in the migration from the actual database description. Please upload to the new `2.4.2` version and let me know if the issue was fixed.

**Comment by ssciolla** [comment]
Hi @Cvmcosta, thanks for the speedy response! Did you mean to push out `2.4.2`? Not seeing it tagged here or on `npm`.

**Comment by Cvmcosta** [comment]
Hello @ssciolla. You are right, i forgot to publish it! I am really sorry, i've extremely busy trying to graduate next week and it seems my brain is starting to fail hahaha.

**Comment by ssciolla** [comment]
No worries, @Cvmcosta, thank you for pushing out the update! Things are working for me now, so I'd say you can close out the issue. I'll follow up if I see any new issues. Good luck with the graduation!
